// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	difficulties "backend/business/difficulties"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// GetAll provides a mock function with given fields: ctx
func (_m *Repository) GetAll(ctx context.Context) ([]difficulties.Domain, error) {
	ret := _m.Called(ctx)

	var r0 []difficulties.Domain
	if rf, ok := ret.Get(0).(func(context.Context) []difficulties.Domain); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]difficulties.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
